name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build
        run: pnpm run -r --workspace-concurrency=1 build
      - name: Build docs
        run: |
          pnpm run docs 
          touch docs/.nojekyll
          echo "ref.mtcute.dev" > docs/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

  # Deployment job
  deploy:
    # do not run on forks and PRs
    if: github.repository == 'mtcute/mtcute' && github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
